### ISSUE TITLE
[1.18.1] ISsue with Tanks causing crashes

### ISSUE THREAD

**Issue by itsdinkd** [Kotori316/FluidTank#89] opened 2022-01-13 18:00 UTC
https://github.com/itsdinkd/AQM2/issues/39

As reported by players of my modpack, there is a crash occurring with liquid tanks. more info can be found at the issue link above

**Comment by Kotori316** [comment] 2022-01-13 23:38
Duplicate of #87 

Why didn't you ask the player to use the latest version(v18.3.0) of mod?

**Closed as completed by Kotori316** 2022-01-13 23:38 UTC
Labels: duplicate

**Comment by itsdinkd** [comment] 2022-02-10 04:51
> Duplicate of #87
> 
> Why didn't you ask the player to use the latest version(v18.3.0) of mod?

I have over 340 mods in my modpack. Clearly I did not know there was an update, nor did I know that update fixed this bug.
